### ISSUE TITLE
请问 音频分类的预测过程C++实现的版本有么？

### ISSUE THREAD

**Issue by mtz1992** [yeyupiaoling/AudioClassification-PaddlePaddle#1]

**Comment by yeyupiaoling** [comment]
@mtz1992 没有呢，你可以看看官方的文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/native_infer.html
根据这个部署

**Comment by mtz1992** [comment]
好的，多谢

**Comment by mtz1992** [comment]
您好，我还有个问题想请教您一下。在训练过程中使用到的测试数据进行模型预测的过程和使用infer文件进行模型预测的过程有什么区别吗？因为我看到在使用reader读取数据时，将音频数据转化为了梅尔特征并裁剪了静音数据，进行的模型训练，而在使用infer进行模型预测时直接使用librosa进行音频文件的读取，不知道这样会不会造成预测的不准确？如果一个文件静音占比太大的话模型该怎样预测呢？

**Comment by yeyupiaoling** [comment]
@mtz1992 在预测infer也一样做处理的
https://github.com/yeyupiaoling/AudioClassification-PaddlePaddle/blob/007eb040c09e8b9bebbe0c8e121e11ee70ba8c05/infer.py#L21-L24

**Comment by mtz1992** [comment]
好的，多谢。我看到您在训练时是使用的音频文件前2.97秒的音频，那么请问在预测时是不是也需要将音频文件切分为每段3秒的音频在进行预测？

**Comment by yeyupiaoling** [comment]
@mtz1992 是的，按照训练的数据预处理一样。
