### ISSUE TITLE
BaiduCN1.2k Model预训练声学模型

### ISSUE THREAD

**Issue by JeremySun1224** [yeyupiaoling/AudioClassification-PaddlePaddle#2]
您好，请问可以加载[预训练声学模型](https://github.com/PaddlePaddle/DeepSpeech)进行音频标签的分类吗

**Comment by yeyupiaoling** [comment]
@JeremySun1224 你说的那个是语音识别，我这个是声音分类。不一样 的。

**Comment by JeremySun1224** [comment]
@yeyupiaoling 好的 谢谢您的回复
