### ISSUE TITLE
训练时报错，提示ValueError: invalid literal for int() with base 10: '知更鸟'

### ISSUE THREAD

**Issue by kslz** [yeyupiaoling/AudioClassification-PaddlePaddle#4]
我看代码的逻辑是要在这里把取到的指转为int
`return spec_mag, np.array(int(label), dtype=np.int64)`
请问是要求train_list.txt 音频路径\t音频对应的类别标签 中的【音频对应的类别标签】必须是数字吗？

**Comment by yeyupiaoling** [comment]
模型分类就是要int标签，类别从0开始。你可以先去学习图像分类

**Comment by kslz** [comment]
> 模型分类就是要int标签，类别从0开始。你可以先去学习图像分类

呃呃 好的 我再问下 路径里可以用中文吗 我看样例里写的是dataset/audio/鸟叫声/······

**Comment by yeyupiaoling** [comment]
可以的

**Comment by kslz** [comment]
> 可以的

thanks
