### ISSUE TITLE
声音异常检测

### ISSUE THREAD

**Issue by SSTato** [yeyupiaoling/AudioClassification-PaddlePaddle#7]
如果我想添加一个声音异常检测功能该怎么做呢，比如我划分了十个类别，当检测到声音不在这十个类别中，就输出其他类别，类似这样的怎么实现呢，我的想法是检测声音对比后返回一个和各类别相似度的分数，低于阈值的就是其他类别。问题是如何用你的代码得到这个分数呢。

**Comment by yeyupiaoling** [comment]
你的想法也是可以的，或者可以把不属于这10类的音频全部当作一类进行训练

得分可以这样拿
```python
score = result[lab]
```

**Comment by SSTato** [comment]
> 你的想法也是可以的，或者可以把不属于这10类的音频全部当作一类进行训练
> 
> 得分可以这样拿
> 
> ```python
> score = result[lab]
> ```

是否应该是score = result[0][lab]

另外infer运行较慢有什么可以加速的方法吗，不知道该代码在infer时是否使用了gpu呢

**Comment by yeyupiaoling** [comment]
是的

看你的环境是安装哪个版本的Paddle，

**Comment by SSTato** [comment]
> 是的
> 
> 看你的环境是安装哪个版本的Paddle，

我使用的是你提供的pytorch版本的代码

**Comment by SSTato** [comment]
> > 是的
> > 看你的环境是安装哪个版本的Paddle，
> 
> 我使用的是你提供的pytorch版本的代码

torch 1.7.1+cu110  NVIDIA GeForce RTX 3060

**Comment by yeyupiaoling** [comment]
Pytorch 的，你在这里提问？

默认是使用GPU的，CPU很慢的。
你的推理速度是多少？

**Comment by zyb8543d** [comment]
> 
result[lab] 这个在哪里啊，在推理代码里没找到

**Comment by SSTato** [comment]
> > 
> 
> result[lab] 这个在哪里啊，在推理代码里没找到

我的代码里有的
